#!/bin/sh
# SPDX-FileCopyrightText: 2020 The TTY Faker for GitHub Actions Authors
# SPDX-FileCopyrightText: Copyright (c) 2020, Yuri6037. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause AND LicenseRef-original

script -q -e -c "$*"
