# SPDX-FileCopyrightText: 2020 The TTY Faker for GitHub Actions Authors
# SPDX-License-Identifier: MIT

name: Continuous Integration
on:
  push:
  schedule:
    - cron: '* 15 * * 0'

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm ci --ignore-scripts
      - run: npm run build
  compliance-reuse:
    name: REUSE Compliance Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fsfe/reuse-action@v1.1
  compliance-fossa:
    name: FOSSA License Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
          fossa init
          fossa analyze
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
  security-snyk:
    name: Snyk Vulnerability Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm ci --ignore-scripts
      - uses: snyk/actions/node@0.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  security-github-code-scanning:
    name: GitHub Code Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm ci --ignore-scripts
      - uses: github/codeql-action/init@v1
        with:
          languages: javascript
      - uses: github/codeql-action/analyze@v1